import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// PlumbPro brand colors
const COLORS = {
  primary: [0, 51, 102],      // #003366
  secondary: [255, 95, 0],    // #FF5F00
  text: [30, 41, 59],         // Slate 800
  lightGray: [241, 245, 249]  // Slate 100
};

// Add header to PDF
const addHeader = (doc, title, subtitle = '') => {
  // Logo/Brand
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, 220, 25, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('PLUMBPRO', 14, 16);
  
  doc.setTextColor(...COLORS.secondary);
  doc.setFontSize(10);
  doc.text('FIELD COMPANION', 65, 16);
  
  // Title
  doc.setTextColor(...COLORS.text);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, 40);
  
  if (subtitle) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139); // Slate 500
    doc.text(subtitle, 14, 48);
  }
  
  return 55; // Return Y position after header
};

// Add footer to PDF
const addFooter = (doc, pageNum, totalPages) => {
  const pageHeight = doc.internal.pageSize.height;
  
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Generated by PlumbPro Field Companion | Page ${pageNum} of ${totalPages}`,
    doc.internal.pageSize.width / 2,
    pageHeight - 10,
    { align: 'center' }
  );
  doc.text(
    new Date().toLocaleString(),
    doc.internal.pageSize.width - 14,
    pageHeight - 10,
    { align: 'right' }
  );
};

// Export timesheet to PDF
export const exportTimesheetPDF = (data) => {
  const doc = new jsPDF();
  
  // Header
  const startY = addHeader(
    doc,
    'TIMESHEET REPORT',
    `Period: ${data.period.start} to ${data.period.end}`
  );
  
  // User info
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.text);
  doc.setFont('helvetica', 'bold');
  doc.text(`Employee: ${data.user.name}`, 14, startY);
  if (data.user.company) {
    doc.setFont('helvetica', 'normal');
    doc.text(`Company: ${data.user.company}`, 14, startY + 6);
  }
  
  // Summary box
  const summaryY = startY + 15;
  doc.setFillColor(...COLORS.lightGray);
  doc.roundedRect(14, summaryY, 180, 25, 2, 2, 'F');
  
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.primary);
  doc.text('SUMMARY', 20, summaryY + 8);
  
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.text);
  doc.text(`Total Hours: ${data.summary.total_hours}`, 20, summaryY + 16);
  doc.text(`Total Entries: ${data.summary.total_entries}`, 80, summaryY + 16);
  doc.text(`Jobs: ${Object.keys(data.summary.jobs_summary).length}`, 140, summaryY + 16);
  
  // Time entries table
  const tableData = data.entries.map(entry => [
    entry.date,
    entry.job_name,
    entry.start_time,
    entry.end_time,
    `${entry.break_minutes}m`,
    `${entry.hours_worked}h`,
    entry.notes || ''
  ]);
  
  autoTable(doc, {
    startY: summaryY + 35,
    head: [['Date', 'Job', 'Start', 'End', 'Break', 'Hours', 'Notes']],
    body: tableData,
    headStyles: {
      fillColor: COLORS.primary,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 9
    },
    bodyStyles: {
      fontSize: 8,
      textColor: COLORS.text
    },
    alternateRowStyles: {
      fillColor: COLORS.lightGray
    },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 40 },
      2: { cellWidth: 18 },
      3: { cellWidth: 18 },
      4: { cellWidth: 15 },
      5: { cellWidth: 15 },
      6: { cellWidth: 'auto' }
    },
    margin: { left: 14, right: 14 }
  });
  
  // Jobs breakdown on new page if there's data
  if (Object.keys(data.summary.jobs_summary).length > 0) {
    doc.addPage();
    addHeader(doc, 'HOURS BY JOB', '');
    
    const jobsData = Object.entries(data.summary.jobs_summary).map(([job, stats]) => [
      job,
      stats.entries,
      `${stats.hours.toFixed(2)}h`
    ]);
    
    autoTable(doc, {
      startY: 55,
      head: [['Job Name', 'Entries', 'Total Hours']],
      body: jobsData,
      headStyles: {
        fillColor: COLORS.primary,
        textColor: [255, 255, 255],
        fontStyle: 'bold'
      },
      bodyStyles: {
        textColor: COLORS.text
      },
      alternateRowStyles: {
        fillColor: COLORS.lightGray
      }
    });
  }
  
  // Add footers
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addFooter(doc, i, pageCount);
  }
  
  // Save
  const fileName = `PlumbPro_Timesheet_${data.period.start}_${data.period.end}.pdf`;
  doc.save(fileName);
  
  return fileName;
};

// Export job bid to PDF
export const exportBidPDF = (data) => {
  const doc = new jsPDF();
  
  // Header
  const startY = addHeader(
    doc,
    'JOB ESTIMATE',
    `Created: ${new Date(data.bid.created_at).toLocaleDateString()}`
  );
  
  // Company/From info
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.text);
  doc.text('FROM:', 14, startY);
  doc.setFont('helvetica', 'normal');
  doc.text(data.user.name, 14, startY + 6);
  if (data.user.company) {
    doc.text(data.user.company, 14, startY + 12);
  }
  doc.text(data.user.email, 14, startY + 18);
  
  // Client/To info
  doc.setFont('helvetica', 'bold');
  doc.text('TO:', 110, startY);
  doc.setFont('helvetica', 'normal');
  doc.text(data.bid.client_name, 110, startY + 6);
  if (data.bid.client_contact) {
    doc.text(data.bid.client_contact, 110, startY + 12);
  }
  
  // Job details box
  const jobY = startY + 30;
  doc.setFillColor(...COLORS.lightGray);
  doc.roundedRect(14, jobY, 180, 35, 2, 2, 'F');
  
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.primary);
  doc.text('JOB DETAILS', 20, jobY + 8);
  
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.text);
  doc.setFontSize(12);
  doc.text(data.bid.job_name, 20, jobY + 18);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(data.bid.description, 20, jobY + 26, { maxWidth: 170 });
  
  // Cost breakdown table
  const tableY = jobY + 45;
  
  const breakdownData = [
    ['Labor', `${data.bid.labor_hours} hours @ $${data.bid.hourly_rate}/hr`, `$${data.bid.labor_cost.toFixed(2)}`],
    ['Materials', 'Materials and supplies', `$${data.bid.material_cost.toFixed(2)}`],
    ['Subtotal', '', `$${(data.bid.labor_cost + data.bid.material_cost).toFixed(2)}`],
    [`Markup (${data.bid.markup_percent}%)`, '', `$${data.bid.markup_amount.toFixed(2)}`]
  ];
  
  autoTable(doc, {
    startY: tableY,
    head: [['Item', 'Description', 'Amount']],
    body: breakdownData,
    headStyles: {
      fillColor: COLORS.primary,
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    bodyStyles: {
      textColor: COLORS.text
    },
    columnStyles: {
      0: { cellWidth: 40, fontStyle: 'bold' },
      1: { cellWidth: 90 },
      2: { cellWidth: 40, halign: 'right' }
    },
    margin: { left: 14, right: 14 }
  });
  
  // Total box
  const finalY = doc.lastAutoTable.finalY + 5;
  doc.setFillColor(...COLORS.primary);
  doc.roundedRect(104, finalY, 90, 20, 2, 2, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('TOTAL ESTIMATE:', 110, finalY + 9);
  doc.setFontSize(16);
  doc.text(`$${data.bid.total_bid.toFixed(2)}`, 185, finalY + 14, { align: 'right' });
  
  // Notes
  if (data.bid.notes) {
    doc.setTextColor(...COLORS.text);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('NOTES:', 14, finalY + 35);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(data.bid.notes, 14, finalY + 42, { maxWidth: 180 });
  }
  
  // Terms
  const termsY = finalY + 60;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('Terms & Conditions:', 14, termsY);
  doc.text('• This estimate is valid for 30 days from the date above.', 14, termsY + 5);
  doc.text('• 50% deposit required to begin work. Balance due upon completion.', 14, termsY + 10);
  doc.text('• Additional work not included in this estimate will be billed separately.', 14, termsY + 15);
  
  // Footer
  addFooter(doc, 1, 1);
  
  // Save
  const fileName = `PlumbPro_Estimate_${data.bid.job_name.replace(/\s+/g, '_')}.pdf`;
  doc.save(fileName);
  
  return fileName;
};

// Export material list to PDF
export const exportMaterialListPDF = (data, userName, company) => {
  const doc = new jsPDF();
  
  // Header
  const startY = addHeader(
    doc,
    'MATERIAL LIST',
    `Job: ${data.job_name}`
  );
  
  // User info
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.text);
  doc.text(`Prepared by: ${userName}`, 14, startY);
  if (company) {
    doc.text(`Company: ${company}`, 14, startY + 6);
  }
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, startY + 12);
  
  // Materials table
  const tableData = data.items.map((item, index) => [
    index + 1,
    item.name,
    item.quantity,
    item.unit,
    `$${item.unit_price.toFixed(2)}`,
    `$${(item.quantity * item.unit_price).toFixed(2)}`,
    item.notes || ''
  ]);
  
  autoTable(doc, {
    startY: startY + 20,
    head: [['#', 'Item', 'Qty', 'Unit', 'Unit Price', 'Total', 'Notes']],
    body: tableData,
    foot: [['', '', '', '', 'TOTAL:', `$${data.total_cost.toFixed(2)}`, '']],
    headStyles: {
      fillColor: COLORS.primary,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 9
    },
    bodyStyles: {
      fontSize: 8,
      textColor: COLORS.text
    },
    footStyles: {
      fillColor: COLORS.secondary,
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: COLORS.lightGray
    },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 45 },
      2: { cellWidth: 15, halign: 'center' },
      3: { cellWidth: 15, halign: 'center' },
      4: { cellWidth: 22, halign: 'right' },
      5: { cellWidth: 22, halign: 'right' },
      6: { cellWidth: 'auto' }
    },
    margin: { left: 14, right: 14 }
  });
  
  // Footer
  addFooter(doc, 1, 1);
  
  // Save
  const fileName = `PlumbPro_Materials_${data.job_name.replace(/\s+/g, '_')}.pdf`;
  doc.save(fileName);
  
  return fileName;
};

export default {
  exportTimesheetPDF,
  exportBidPDF,
  exportMaterialListPDF
};
