import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import axios from "axios";
import { API } from "@/App";
import {
  Wrench, Shield, Clock, Calculator, FileText, BookOpen,
  CheckCircle, Star, ChevronRight, Zap, Crown, Building,
  Smartphone, Users, ArrowRight, MapPin, DollarSign
} from "lucide-react";

export default function LandingPage() {
  const navigate = useNavigate();
  const [promoStatus, setPromoStatus] = useState(null);

  useEffect(() => {
    axios.get(`${API}/promo/status`).then(res => setPromoStatus(res.data)).catch(() => {});
  }, []);

  const spotsLeft = promoStatus?.spots_remaining ?? 0;
  const promoActive = promoStatus?.promo_active ?? true;

  const features = [
    { icon: FileText, title: "Field Notes", desc: "Track jobs, add photos, stay organized on every call" },
    { icon: Calculator, title: "Plumbing Formulas", desc: "Pipe sizing, flow rates, pressure calcs at your fingertips" },
    { icon: Shield, title: "AI Safety Talks", desc: "Fresh daily safety talks generated by AI for your crew" },
    { icon: Clock, title: "Timesheets", desc: "GPS clock-in/out, geofencing, automatic time tracking" },
    { icon: DollarSign, title: "Job Bidding", desc: "Create professional bids and email them straight to clients" },
    { icon: BookOpen, title: "2015 UPC Code", desc: "Full Uniform Plumbing Code reference — searchable in the field" },
    { icon: MapPin, title: "Total Station", desc: "Grade calculations, elevation tracking for pipe runs" },
    { icon: Wrench, title: "Material Lists", desc: "Build material lists per job with cost tracking" },
  ];

  const tiers = [
    {
      id: "basic", name: "Basic", price: "4.99", icon: Zap, color: "bg-[#003366]",
      features: ["Notes & Job Tracking", "Calculator & Formulas", "OSHA Reference", "Safety Data Sheets", "UPC Code Reference"]
    },
    {
      id: "pro", name: "Pro", price: "9.99", icon: Crown, color: "bg-[#FF5F00]", popular: true,
      features: ["Everything in Basic", "AI Safety Talks", "Timesheet & GPS Tracking", "Material Lists", "Calendar & Scheduling", "PDF Exports"]
    },
    {
      id: "enterprise", name: "Enterprise", price: "19.99", icon: Building, color: "bg-[#003366]",
      features: ["Everything in Pro", "Job Bidding & Estimates", "Email Bid Sharing", "Unlimited Blueprints", "Priority Support"]
    },
  ];

  return (
    <div className="min-h-screen bg-slate-900 text-white" data-testid="landing-page">
      {/* Promo Banner */}
      {promoActive && (
        <div className="bg-[#FF5F00] text-white text-center py-2.5 px-4 text-sm font-bold tracking-wide" data-testid="promo-banner">
          FIRST 100 USERS GET 3 MONTHS FREE — {spotsLeft} SPOTS LEFT
        </div>
      )}

      {/* Hero Section */}
      <header className="relative overflow-hidden">
        <div
          className="absolute inset-0 bg-cover bg-center"
          style={{
            backgroundImage: `url('https://images.pexels.com/photos/8960990/pexels-photo-8960990.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940')`,
          }}
        />
        <div className="absolute inset-0 bg-gradient-to-b from-slate-900/80 via-slate-900/70 to-slate-900" />

        <div className="relative z-10 max-w-6xl mx-auto px-4 py-20 md:py-32">
          <div className="max-w-3xl">
            <Badge className="bg-[#FF5F00]/20 text-[#FF5F00] border border-[#FF5F00]/40 font-bold text-xs uppercase tracking-widest mb-6 px-3 py-1">
              Built by a Plumber, for Plumbers
            </Badge>
            <h1 className="font-heading text-5xl sm:text-6xl lg:text-7xl font-extrabold tracking-tight leading-none uppercase">
              PLUMB<span className="text-[#FF5F00]">PRO</span>
            </h1>
            <p className="text-xl md:text-2xl text-slate-300 mt-4 leading-relaxed max-w-2xl">
              The field companion app that works as hard as you do. Formulas, timesheets, safety talks, plumbing code, and job bidding — all in your pocket.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 mt-8">
              <Button
                onClick={() => navigate("/login")}
                className="h-14 px-8 bg-[#FF5F00] hover:bg-[#FF5F00]/90 text-white font-bold uppercase tracking-wide text-lg rounded-sm"
                data-testid="hero-cta-btn"
              >
                {promoActive ? "Claim Your Free 3 Months" : "Start Free Trial"}
                <ArrowRight className="w-5 h-5 ml-2" />
              </Button>
              <Button
                onClick={() => document.getElementById("features")?.scrollIntoView({ behavior: "smooth" })}
                variant="outline"
                className="h-14 px-8 border-2 border-white/30 text-white hover:bg-white/10 font-bold uppercase tracking-wide rounded-sm"
                data-testid="hero-features-btn"
              >
                See Features
              </Button>
            </div>
            {promoActive && (
              <p className="mt-4 text-sm text-[#FF5F00] font-bold">
                Only {spotsLeft} spots remaining for the 3-month free offer
              </p>
            )}
          </div>
        </div>
      </header>

      {/* Trust Bar */}
      <section className="bg-[#003366] py-5 border-y border-[#003366]/60">
        <div className="max-w-6xl mx-auto px-4 flex flex-wrap justify-center gap-8 md:gap-16 items-center text-center">
          <div>
            <p className="text-2xl font-bold text-white">15+</p>
            <p className="text-xs text-slate-300 uppercase tracking-wide">Field Tools</p>
          </div>
          <div>
            <p className="text-2xl font-bold text-white">2015 UPC</p>
            <p className="text-xs text-slate-300 uppercase tracking-wide">Code Reference</p>
          </div>
          <div>
            <p className="text-2xl font-bold text-[#FF5F00]">AI</p>
            <p className="text-xs text-slate-300 uppercase tracking-wide">Safety Talks</p>
          </div>
          <div>
            <p className="text-2xl font-bold text-white">GPS</p>
            <p className="text-xs text-slate-300 uppercase tracking-wide">Time Tracking</p>
          </div>
          <div className="flex items-center gap-1">
            <Smartphone className="w-5 h-5 text-[#FF5F00]" />
            <p className="text-xs text-slate-300 uppercase tracking-wide">Works on Any Phone</p>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section id="features" className="py-16 md:py-24 bg-slate-900">
        <div className="max-w-6xl mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="font-heading text-3xl md:text-4xl font-bold uppercase tracking-tight">
              Everything You Need <span className="text-[#FF5F00]">in the Field</span>
            </h2>
            <p className="text-slate-400 mt-3 max-w-xl mx-auto">
              Stop juggling notebooks, calculators, and code books. PlumbPro puts it all in one app.
            </p>
          </div>

          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4" data-testid="features-grid">
            {features.map((feature, i) => {
              const Icon = feature.icon;
              return (
                <Card key={i} className="bg-slate-800 border-slate-700 hover:border-[#FF5F00]/50 transition-colors group">
                  <CardContent className="p-5">
                    <div className="w-11 h-11 bg-[#FF5F00]/10 rounded-sm flex items-center justify-center mb-3 group-hover:bg-[#FF5F00]/20 transition-colors">
                      <Icon className="w-5 h-5 text-[#FF5F00]" strokeWidth={2.5} />
                    </div>
                    <h3 className="font-bold text-white mb-1">{feature.title}</h3>
                    <p className="text-sm text-slate-400">{feature.desc}</p>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>
      </section>

      {/* Built by a Plumber Section */}
      <section className="py-16 md:py-24 bg-slate-800/50">
        <div className="max-w-6xl mx-auto px-4 grid md:grid-cols-2 gap-12 items-center">
          <div>
            <Badge className="bg-[#FF5F00]/20 text-[#FF5F00] border border-[#FF5F00]/40 mb-4">Our Story</Badge>
            <h2 className="font-heading text-3xl md:text-4xl font-bold uppercase tracking-tight">
              Built by a <span className="text-[#FF5F00]">Plumber</span>
            </h2>
            <p className="text-slate-300 mt-4 leading-relaxed">
              PlumbPro was born on job sites, not in a tech office. After years of carrying code books, scribbling on notepads, and losing track of hours — we built the app we wished we had.
            </p>
            <ul className="mt-6 space-y-3">
              {[
                "Every feature solves a real problem plumbers face daily",
                "Works offline — because job sites don't always have signal",
                "Big buttons and clear text — designed for gloved hands",
                "UPC code reference you can actually search in the field",
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-3">
                  <CheckCircle className="w-5 h-5 text-[#FF5F00] flex-shrink-0 mt-0.5" />
                  <span className="text-slate-300 text-sm">{item}</span>
                </li>
              ))}
            </ul>
          </div>
          <div className="relative">
            <img
              src="https://images.pexels.com/photos/6419128/pexels-photo-6419128.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
              alt="Plumber at work"
              className="rounded-sm border-2 border-slate-700 shadow-2xl"
            />
            <div className="absolute -bottom-4 -right-4 bg-[#FF5F00] text-white px-4 py-2 rounded-sm font-bold text-sm uppercase">
              Field Tested
            </div>
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section id="pricing" className="py-16 md:py-24 bg-slate-900">
        <div className="max-w-6xl mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="font-heading text-3xl md:text-4xl font-bold uppercase tracking-tight">
              Simple <span className="text-[#FF5F00]">Pricing</span>
            </h2>
            {promoActive ? (
              <p className="text-[#FF5F00] font-bold mt-3">
                First 100 users get 3 months FREE on any plan — {spotsLeft} spots left!
              </p>
            ) : (
              <p className="text-slate-400 mt-3">Start with a 7-day free trial. Cancel anytime.</p>
            )}
          </div>

          <div className="grid gap-6 md:grid-cols-3 max-w-4xl mx-auto" data-testid="pricing-grid">
            {tiers.map((tier) => {
              const Icon = tier.icon;
              return (
                <Card
                  key={tier.id}
                  className={`relative bg-slate-800 border-slate-700 ${tier.popular ? "border-2 border-[#FF5F00] scale-105" : ""}`}
                  data-testid={`landing-tier-${tier.id}`}
                >
                  {tier.popular && (
                    <div className="absolute -top-3 left-1/2 -translate-x-1/2">
                      <Badge className="bg-[#FF5F00] text-white font-bold uppercase text-xs">Most Popular</Badge>
                    </div>
                  )}
                  <CardContent className="p-6 text-center">
                    <div className={`w-14 h-14 mx-auto mb-4 ${tier.color} rounded-sm flex items-center justify-center`}>
                      <Icon className="w-7 h-7 text-white" />
                    </div>
                    <h3 className="font-heading text-2xl font-bold uppercase text-white">{tier.name}</h3>
                    <div className="mt-3">
                      <span className="text-4xl font-bold text-white">${tier.price}</span>
                      <span className="text-slate-400">/mo</span>
                    </div>
                    {promoActive && (
                      <p className="text-[#FF5F00] text-xs font-bold mt-1">3 MONTHS FREE FOR EARLY BIRDS</p>
                    )}
                    <ul className="mt-5 space-y-2 text-left">
                      {tier.features.map((f, i) => (
                        <li key={i} className="flex items-start gap-2 text-sm text-slate-300">
                          <CheckCircle className="w-4 h-4 text-green-400 flex-shrink-0 mt-0.5" />
                          <span>{f}</span>
                        </li>
                      ))}
                    </ul>
                    <Button
                      onClick={() => navigate("/login")}
                      className={`w-full h-12 mt-6 font-bold uppercase tracking-wide rounded-sm ${
                        tier.popular
                          ? "bg-[#FF5F00] hover:bg-[#FF5F00]/90 text-white"
                          : "bg-[#003366] hover:bg-[#003366]/90 text-white"
                      }`}
                      data-testid={`landing-select-${tier.id}`}
                    >
                      {promoActive ? "Start Free" : "Start Trial"}
                    </Button>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-16 md:py-20 bg-[#003366]">
        <div className="max-w-3xl mx-auto px-4 text-center">
          <h2 className="font-heading text-3xl md:text-4xl font-bold uppercase tracking-tight">
            Ready to Work <span className="text-[#FF5F00]">Smarter</span>?
          </h2>
          <p className="text-slate-300 mt-4 text-lg">
            Join the plumbers who are ditching the notebooks and going digital. Sign up takes 30 seconds.
          </p>
          <Button
            onClick={() => navigate("/login")}
            className="h-14 px-10 mt-8 bg-[#FF5F00] hover:bg-[#FF5F00]/90 text-white font-bold uppercase tracking-wide text-lg rounded-sm"
            data-testid="final-cta-btn"
          >
            {promoActive ? `Claim 3 Months Free (${spotsLeft} left)` : "Get Started Free"}
            <ArrowRight className="w-5 h-5 ml-2" />
          </Button>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-slate-900 border-t border-slate-800 py-8">
        <div className="max-w-6xl mx-auto px-4 flex flex-col md:flex-row justify-between items-center gap-4">
          <div>
            <h3 className="font-heading text-xl font-bold">
              PLUMB<span className="text-[#FF5F00]">PRO</span>
            </h3>
            <p className="text-xs text-slate-500 mt-1">Field Companion for Professional Plumbers</p>
          </div>
          <p className="text-xs text-slate-500">&copy; {new Date().getFullYear()} PlumbPro. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
